import { createStore } from '@stencil/store';

export interface ILocale {
  entries: TLocaleLocalizedWordsEntries;
  direction: 'ltr' | 'rtl';
}
export type TLocaleLocalizedWordsEntries = {
  Lcz_AcceptedCreditCards: string;
  Lcz_Activities: string;
  Lcz_Adult: string;
  Lcz_Adults: string;
  Lcz_Age: string;
  Lcz_Ages: string;
  Lcz_AlreadyHaveAnAccount: string;
  Lcz_Amenities: string;
  Lcz_AnyMessageForUs: string;
  Lcz_Apply: string;
  Lcz_ArrivalDate: string;
  Lcz_ArrivalHour: string;
  Lcz_ArrivalTime: string;
  Lcz_At: string;
  Lcz_Balance: string;
  Lcz_Before: string;
  Lcz_BookedBy: string;
  Lcz_BookingCode: string;
  Lcz_BookingPreference: string;
  Lcz_BookNow: string;
  Lcz_Cancel: string;
  Lcz_CancelBooking: string;
  Lcz_CardNumber: string;
  Lcz_CarModel: string;
  Lcz_ChangeDetails: string;
  Lcz_CheckIn: string;
  Lcz_CheckInFromUntil: string;
  Lcz_CheckOut: string;
  Lcz_Child: string;
  Lcz_Children: string;
  Lcz_Close: string;
  Lcz_CompleteYourAccount: string;
  Lcz_Conditions: string;
  Lcz_ConfirmBooking: string;
  Lcz_Contact: string;
  Lcz_ContinueWithFacebook: string;
  Lcz_ContinueWithGoogle: string;
  Lcz_Country: string;
  Lcz_CreateAnAccount: string;
  Lcz_Cvc: string;
  Lcz_Dates: string;
  Lcz_DiscountApplied: string;
  Lcz_Done: string;
  Lcz_DontHaveAnAccount: string;
  Lcz_DueAmountNow: string;
  Lcz_EmailAddress: string;
  Lcz_EnterYourCouponCode: string;
  Lcz_EnterYourEmail: string;
  Lcz_EnterYourFirstName: string;
  Lcz_EnterYourLastName: string;
  Lcz_EnterYourPassword: string;
  Lcz_ExpirationDate: string;
  Lcz_FacilitiesAndServices: string;
  Lcz_FirstName: string;
  Lcz_FlightDetails: string;
  Lcz_FoodAndbeverage: string;
  Lcz_ForgotPassword: string;
  Lcz_FreeInternet: string;
  Lcz_From: string;
  Lcz_GetDirections: string;
  Lcz_GetLoyaltyDiscount: string;
  Lcz_GuestFullName: string;
  Lcz_GuestName: string;
  Lcz_Guests: string;
  Lcz_HaveAgentorCoporate: string;
  Lcz_HaveCoupon: string;
  Lcz_IAgreePrivacyPolicy: string;
  Lcz_IAmBooklingForSomeoneElse: string;
  Lcz_IfICancel: string;
  Lcz_ImportantInformation: string;
  Lcz_InvalidAgentCode: string;
  Lcz_LastName: string;
  Lcz_Location: string;
  Lcz_LoyaltyApplied: string;
  Lcz_Maximum: string;
  Lcz_MealPlan: string;
  Lcz_MessageProperty: string;
  Lcz_MobileNumber: string;
  Lcz_MoreDetails: string;
  Lcz_NameOnCard: string;
  Lcz_NeedPickup: string;
  Lcz_night: string;
  Lcz_Nights: string;
  Lcz_NonRefundable: string;
  Lcz_NoOfVehicles: string;
  Lcz_NoThankYou: string;
  Lcz_Or: string;
  Lcz_PaidInternet: string;
  Lcz_PaymentDetails: string;
  Lcz_PayNow: string;
  Lcz_Person: string;
  Lcz_Persons: string;
  Lcz_Phone: string;
  Lcz_PickupFee: string;
  Lcz_Policy: string;
  Lcz_PropertyFacilities: string;
  Lcz_PublicAreas: string;
  Lcz_RequiredCapacity: string;
  Lcz_RetryPayment: string;
  Lcz_Room: string;
  Lcz_Rooms: string;
  Lcz_Search: string;
  Lcz_SecurityCode: string;
  Lcz_SecurityCodeHint: string;
  Lcz_Select: string;
  Lcz_SelectYourPaymentMethod: string;
  Lcz_Services: string;
  Lcz_SiginIntToYourAccount: string;
  Lcz_SignIn: string;
  Lcz_SignInOrCreateToBookFaster: string;
  Lcz_SignUp: string;
  Lcz_Total: string;
  Lcz_Travelers: string;
  Lcz_ViewConditions: string;
  Lcz_wifi: string;
  Lcz_YesFrom: string;
  Lcz_YouHavePaid: string;
  Lcz_YouMustAcceptPrivacyPolicy: string;
  Lcz_YourArrivalTime: string;
  Lcz_YourCardWillBeCharged: string;
};

const initialState: ILocale = {
  entries: null,
  direction: 'ltr',
};
export const { state: localizedWords, onChange: onCalendarDatesChange } = createStore<ILocale>(initialState);

export default localizedWords;
