export const data = {
  booking_nbr: '30858170342',
  roomtypes: [
    {
      amenities: [
        {
          amenity_type: 'room',
          code: 'amenities',
          description: 'Welcome amenities',
        },
        {
          amenity_type: 'room',
          code: 'viewslopes',
          description: 'Slopes view',
        },
        {
          amenity_type: 'room',
          code: 'soundproof',
          description: 'Soundproof',
        },
      ],
      availabilities: null,
      bedding_setup: [
        {
          code: 'kingsizebed',
          count: 1,
          name: 'King size bed',
        },
        {
          code: 'singlebed',
          count: 1,
          name: 'Single bed',
        },
      ],
      description:
        'Our Modern and Classic Rooms averages 322 square feet with custom furnishings,every room in Hotel High Season includes the finest attention to detail, from the triple-sheeted 300 thread count sheets to the one-touch “Goodnight” button.Each room will be everything you are looking for in a Lebanon hotel, and drastically more than you thought possible and our custom beds by will make you want to snooze through your morning plans.When you enter our Modern and Classic Room, you’ll only have one thought: this is what all hotels at Lebanon should be like. ',
      exposed_inventory: null,
      id: 110,
      images: [
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_235.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_271.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_224.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_251.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_225.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_236.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_241.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_234.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_223.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_231.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_226.jpg',
        },
        {
          tooltip: 'Standard Rooms',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_229.jpg',
        },
      ],
      inventory: 2,
      is_active: true,
      is_bed_configuration_enabled: false,
      main_image: {
        tooltip: 'Standard Rooms',
        url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_235.jpg',
      },
      name: 'Standard Rooms',
      occupancy_default: {
        adult_nbr: 2,
        children_nbr: 0,
        infant_nbr: null,
      },
      occupancy_max: {
        adult_nbr: 2,
        children_nbr: 0,
        infant_nbr: 0,
      },
      physicalrooms: [
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 16,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Naji Tanjara',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 24,
          name: '01',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 7,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Matilda',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 25,
          name: '02',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 7,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Matilda',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 14,
          name: '03',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 7,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Matilda',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 15,
          name: '04',
        },
        {
          calendar_cell: null,
          housekeeper: null,
          id: 16,
          name: '05',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 8,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Ahmad',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 17,
          name: '06',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 7,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Matilda',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 26,
          name: '07',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 8,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Ahmad',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 28,
          name: '08',
        },
      ],
      rate: null,
      rateplans: [
        {
          assignable_units: null,
          cancelation:
            '<u><b>Cancellation</b></u>: Free cancellation before Monday, 9 Sep 2024, 22:00.\r\nOne night (of the total price will be charged) if cancelled before  Saturday, 14 Sep 2024, 22:00.\r\n100% of the total price will be charged if cancelled after Saturday, 14 Sep 2024, 22:00 or in case of no show.\r\n',
          custom_text: null,
          guarantee: '<u><b>Guarantee</b></u>: The total price of the reservation may be charged anytime after booking',
          id: 2001,
          is_active: true,
          is_booking_engine_enabled: true,
          is_channel_enabled: true,
          is_closed: false,
          is_non_refundable: true,
          is_targeting_travel_agency: false,
          name: 'Standard Rooms/Bed-&-breakfast/Non-ref./Dem',
          pre_payment_amount: 240.0,
          pre_payment_amount_gross: 266.4,
          rate_restrictions: null,
          selected_variation: null,
          sell_mode: {
            code: '001',
            description: 'Per Room',
          },
          short_name: 'Bed & breakfast',
          variations: [
            {
              IS_MLS_VIOLATED: false,
              MLS_ALERT: null,
              adult_child_offering: '2 adults',
              adult_nbr: 2,
              amount: 204.0,
              amount_gross: 226.44,
              amount_per_night: 68.0,
              child_nbr: 0,
              discount_pct: 15,
              is_lmd: false,
              nights_nbr: 3,
              total_before_discount: 240.0,
            },
          ],
        },
        {
          assignable_units: null,
          cancelation:
            '<u><b>Cancellation</b></u>: Free cancellation before Monday, 9 Sep 2024, 22:00.\r\nOne night (of the total price will be charged) if cancelled before  Saturday, 14 Sep 2024, 22:00.\r\n100% of the total price will be charged if cancelled after Saturday, 14 Sep 2024, 22:00 or in case of no show.\r\n',
          custom_text: 'WS',
          guarantee: '<u><b>Guarantee</b></u>: First night from your booking will be charged.',
          id: 3156,
          is_active: true,
          is_booking_engine_enabled: false,
          is_channel_enabled: false,
          is_closed: null,
          is_non_refundable: false,
          is_targeting_travel_agency: false,
          name: 'Standard Rooms/WS/Bed-only',
          pre_payment_amount: 100.0,
          pre_payment_amount_gross: 111.0,
          rate_restrictions: null,
          selected_variation: null,
          sell_mode: {
            code: '001',
            description: 'Per Room',
          },
          short_name: 'Bed only',
          variations: null,
        },
        {
          assignable_units: null,
          cancelation:
            '<u><b>Cancellation</b></u>: Free cancellation before Monday, 9 Sep 2024, 22:00.\r\nOne night (of the total price will be charged) if cancelled before  Saturday, 14 Sep 2024, 22:00.\r\n100% of the total price will be charged if cancelled after Saturday, 14 Sep 2024, 22:00 or in case of no show.\r\n',
          custom_text: 'Breakfast at $7/person',
          guarantee: '<u><b>Guarantee</b></u>: First night from your booking will be charged.',
          id: 3882,
          is_active: true,
          is_booking_engine_enabled: true,
          is_channel_enabled: false,
          is_closed: false,
          is_non_refundable: false,
          is_targeting_travel_agency: false,
          name: 'Standard Rooms/Breakfast at $7/person/Bed-only',
          pre_payment_amount: 120.0,
          pre_payment_amount_gross: 133.2,
          rate_restrictions: null,
          selected_variation: null,
          sell_mode: {
            code: '001',
            description: 'Per Room',
          },
          short_name: 'Bed only',
          variations: [
            {
              IS_MLS_VIOLATED: false,
              MLS_ALERT: null,
              adult_child_offering: '2 adults',
              adult_nbr: 2,
              amount: 306.0,
              amount_gross: 339.66,
              amount_per_night: 102.0,
              child_nbr: 0,
              discount_pct: 15,
              is_lmd: false,
              nights_nbr: 3,
              total_before_discount: 360.0,
            },
          ],
        },
      ],
      size: 25.0,
      smoking_option: {
        allowed_smoking_options: [
          {
            code: '002',
            description: 'Non-smoking',
          },
        ],
        code: '003',
        description: 'Non smoking',
      },
    },
    {
      amenities: [
        {
          amenity_type: 'room',
          code: 'jacuzzi',
          description: 'Jacuzzi',
        },
        {
          amenity_type: 'room',
          code: 'view',
          description: 'Scenic view',
        },
        {
          amenity_type: 'room',
          code: 'terracegrass',
          description: 'Terrace with grass',
        },
        {
          amenity_type: 'room',
          code: 'bathroomshared',
          description: 'Shared bathroom',
        },
      ],
      availabilities: null,
      bedding_setup: [
        {
          code: 'kingsizebed',
          count: 1,
          name: 'King size bed',
        },
      ],
      description: 'Large room with sitting area and Jacuzzi',
      exposed_inventory: null,
      id: 111,
      images: [
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_221.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_224.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_251.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_225.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_222.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_234.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_223.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_231.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_226.jpg',
        },
        {
          tooltip: 'Premium Suites',
          url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_229.jpg',
        },
      ],
      inventory: 4,
      is_active: true,
      is_bed_configuration_enabled: false,
      main_image: {
        tooltip: 'Premium Suites',
        url: 'https://dhl6m8m6g2w2j.cloudfront.net/ac/AcImage_42_221.jpg',
      },
      name: 'Premium Suites',
      occupancy_default: {
        adult_nbr: 2,
        children_nbr: 0,
        infant_nbr: null,
      },
      occupancy_max: {
        adult_nbr: 5,
        children_nbr: 0,
        infant_nbr: 0,
      },
      physicalrooms: [
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 10,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Bassam',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 2,
          name: '101',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 7,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Matilda',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 3,
          name: '102',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 8,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Ahmad',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 4,
          name: '103',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 7,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Matilda',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 5,
          name: '104',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 8,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Ahmad',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 6,
          name: '105',
        },
        {
          calendar_cell: null,
          housekeeper: {
            assigned_units: null,
            id: 7,
            is_active: false,
            is_soft_deleted: false,
            mobile: null,
            name: 'Matilda',
            note: null,
            password: null,
            phone_prefix: null,
            property_id: 0,
            username: null,
          },
          id: 1,
          name: '106',
        },
      ],
      rate: null,
      rateplans: [
        {
          assignable_units: null,
          cancelation:
            '<u><b>Cancellation</b></u>: Free cancellation before Monday, 9 Sep 2024, 22:00.\r\nOne night (of the total price will be charged) if cancelled before  Saturday, 14 Sep 2024, 22:00.\r\n100% of the total price will be charged if cancelled after Saturday, 14 Sep 2024, 22:00 or in case of no show.\r\n',
          custom_text: 'Breakfast & dinner',
          guarantee: '<u><b>Guarantee</b></u>: First night from your booking will be charged.',
          id: 3755,
          is_active: true,
          is_booking_engine_enabled: true,
          is_channel_enabled: false,
          is_closed: false,
          is_non_refundable: false,
          is_targeting_travel_agency: false,
          name: 'Premium Suites/Breakfast & dinner/Half-board',
          pre_payment_amount: 120.0,
          pre_payment_amount_gross: 133.2,
          rate_restrictions: null,
          selected_variation: null,
          sell_mode: {
            code: '001',
            description: 'Per Room',
          },
          short_name: 'Half board',
          variations: [
            {
              IS_MLS_VIOLATED: false,
              MLS_ALERT: null,
              adult_child_offering: '2 adults',
              adult_nbr: 2,
              amount: 306.0,
              amount_gross: 339.66,
              amount_per_night: 102.0,
              child_nbr: 0,
              discount_pct: 15,
              is_lmd: false,
              nights_nbr: 3,
              total_before_discount: 360.0,
            },
          ],
        },
      ],
      size: 50.0,
      smoking_option: {
        allowed_smoking_options: [
          {
            code: '',
            description: 'No preferences',
          },
          {
            code: '001',
            description: 'Smoking',
          },
          {
            code: '002',
            description: 'Non-smoking',
          },
        ],
        code: '001',
        description: 'Ask',
      },
    },
    {
      amenities: [
        {
          amenity_type: 'room',
          code: 'cablesatellitetv',
          description: 'Cable / Satellite TV',
        },
        {
          amenity_type: 'room',
          code: 'cdplayer',
          description: 'CD player',
        },
        {
          amenity_type: 'room',
          code: 'newspaperfree',
          description: 'Complimentary newspaper',
        },
        {
          amenity_type: 'room',
          code: 'faxmachine',
          description: 'Fax machine',
        },
        {
          amenity_type: 'room',
          code: 'directphone',
          description: 'Direct-dial phone',
        },
        {
          amenity_type: 'room',
          code: 'bathtub',
          description: 'Bathtub',
        },
        {
          amenity_type: 'room',
          code: 'hairdryeronrequest',
          description: 'Hair dryer on request',
        },
        {
          amenity_type: 'room',
          code: 'espressomachine',
          description: 'Espresso machine',
        },
      ],
      availabilities: null,
      bedding_setup: [
        {
          code: 'twinqueenbeds',
          count: 4,
          name: 'Twin queen beds',
        },
        {
          code: 'bunkbeds',
          count: 1,
          name: 'Bunk beds',
        },
        {
          code: 'twindoublechangeable',
          count: 1,
          name: 'Twin/Double changeable beds',
        },
        {
          code: 'sofabed',
          count: 6,
          name: 'Sofa bed',
        },
      ],
      description: '',
      exposed_inventory: null,
      id: 2352,
      images: [],
      inventory: 3,
      is_active: true,
      is_bed_configuration_enabled: true,
      main_image: null,
      name: 'Penthouse',
      occupancy_default: {
        adult_nbr: 2,
        children_nbr: 0,
        infant_nbr: null,
      },
      occupancy_max: {
        adult_nbr: 2,
        children_nbr: 0,
        infant_nbr: 0,
      },
      physicalrooms: [
        {
          calendar_cell: null,
          housekeeper: null,
          id: 317,
          name: 'P1',
        },
        {
          calendar_cell: null,
          housekeeper: null,
          id: 318,
          name: 'P2',
        },
        {
          calendar_cell: null,
          housekeeper: null,
          id: 319,
          name: 'P3',
        },
        {
          calendar_cell: null,
          housekeeper: null,
          id: 320,
          name: 'P4',
        },
      ],
      rate: null,
      rateplans: [
        {
          assignable_units: null,
          cancelation:
            '<u><b>Cancellation</b></u>: Free cancellation before Monday, 9 Sep 2024, 22:00.\r\nOne night (of the total price will be charged) if cancelled before  Saturday, 14 Sep 2024, 22:00.\r\n100% of the total price will be charged if cancelled after Saturday, 14 Sep 2024, 22:00 or in case of no show.\r\n',
          custom_text: '',
          guarantee: '<u><b>Guarantee</b></u>: First night from your booking will be charged.',
          id: 3766,
          is_active: true,
          is_booking_engine_enabled: true,
          is_channel_enabled: false,
          is_closed: false,
          is_non_refundable: false,
          is_targeting_travel_agency: false,
          name: 'Penthouse/Bed-&-breakfast',
          pre_payment_amount: 120.0,
          pre_payment_amount_gross: 133.2,
          rate_restrictions: null,
          selected_variation: null,
          sell_mode: {
            code: '001',
            description: 'Per Room',
          },
          short_name: 'Bed & breakfast',
          variations: [
            {
              IS_MLS_VIOLATED: false,
              MLS_ALERT: null,
              adult_child_offering: '2 adults',
              adult_nbr: 2,
              amount: 360.0,
              amount_gross: 399.6,
              amount_per_night: 120.0,
              child_nbr: 0,
              discount_pct: 0,
              is_lmd: false,
              nights_nbr: 3,
              total_before_discount: 360.0,
            },
          ],
        },
        {
          assignable_units: null,
          cancelation:
            '<u><b>Cancellation</b></u>: Free cancellation before Monday, 9 Sep 2024, 22:00.\r\nOne night (of the total price will be charged) if cancelled before  Saturday, 14 Sep 2024, 22:00.\r\n100% of the total price will be charged if cancelled after Saturday, 14 Sep 2024, 22:00 or in case of no show.\r\n',
          custom_text: 'Bone fire express and 30 minutes massage or yoga',
          guarantee: '<u><b>Guarantee</b></u>: First night from your booking will be charged.',
          id: 3929,
          is_active: true,
          is_booking_engine_enabled: true,
          is_channel_enabled: false,
          is_closed: false,
          is_non_refundable: false,
          is_targeting_travel_agency: false,
          name: 'Penthouse/Bone fire express and 30 minutes massage or yoga/All-inclusive',
          pre_payment_amount: 150.0,
          pre_payment_amount_gross: 166.5,
          rate_restrictions: null,
          selected_variation: null,
          sell_mode: {
            code: '001',
            description: 'Per Room',
          },
          short_name: 'All-inclusive',
          variations: [
            {
              IS_MLS_VIOLATED: false,
              MLS_ALERT: null,
              adult_child_offering: '2 adults',
              adult_nbr: 2,
              amount: 450.0,
              amount_gross: 499.5,
              amount_per_night: 150.0,
              child_nbr: 0,
              discount_pct: 0,
              is_lmd: false,
              nights_nbr: 3,
              total_before_discount: 450.0,
            },
          ],
        },
        {
          assignable_units: null,
          cancelation:
            '<u><b>Cancellation</b></u>: Free cancellation before Monday, 9 Sep 2024, 22:00.\r\nOne night (of the total price will be charged) if cancelled before  Saturday, 14 Sep 2024, 22:00.\r\n100% of the total price will be charged if cancelled after Saturday, 14 Sep 2024, 22:00 or in case of no show.\r\n',
          custom_text: 'WS',
          guarantee: '<u><b>Guarantee</b></u>: First night from your booking will be charged.',
          id: 3942,
          is_active: true,
          is_booking_engine_enabled: false,
          is_channel_enabled: false,
          is_closed: null,
          is_non_refundable: false,
          is_targeting_travel_agency: false,
          name: 'Penthouse/WS/Bed-&-breakfast',
          pre_payment_amount: 100.0,
          pre_payment_amount_gross: 111.0,
          rate_restrictions: null,
          selected_variation: null,
          sell_mode: {
            code: '001',
            description: 'Per Room',
          },
          short_name: 'Bed & breakfast',
          variations: null,
        },
      ],
      size: 100.0,
      smoking_option: {
        allowed_smoking_options: [
          {
            code: '002',
            description: 'Non-smoking',
          },
        ],
        code: '003',
        description: 'Non smoking',
      },
    },
  ],
  tax_statement: 'Including 5.00% City Tax - Excluding 11.00% VAT',
};
